### ISSUE TITLE
erratic behavior in VI Display

### ISSUE THREAD

**Issue by ttsesm** [rgsouthall/vi-suite06#10]
When I try to use the `VI Display` to visualize the calculation results if I enable the `Point visualization` and browse around the model to see the values from different angle and distance these disappear or do not show up at all:

While doing this, the following errors mostly show up in the console:
```
Traceback (most recent call last):
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 3343, in draw_linum
    self.legend_num.draw(context)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 377, in draw
    self.update(context)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 423, in update
    (faces, pcs, depths) = map(list, zip(*[[f, face2d[fi], distances[fi]] for fi, f in enumerate(faces) if face2d[fi] and 0 < face2d[fi][0] < self.width and 0 < face2d[fi][1] < self.height]))          
ValueError: not enough values to unpack (expected 3, got 0)
Traceback (most recent call last):
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 3343, in draw_linum
    self.legend_num.draw(context)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 377, in draw
    self.update(context)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 423, in update
    (faces, pcs, depths) = map(list, zip(*[[f, face2d[fi], distances[fi]] for fi, f in enumerate(faces) if face2d[fi] and 0 < face2d[fi][0] < self.width and 0 < face2d[fi][1] < self.height]))          
ValueError: not enough values to unpack (expected 3, got 0)
Traceback (most recent call last):
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 3343, in draw_linum
    self.legend_num.draw(context)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 377, in draw
    self.update(context)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 423, in update
    (faces, pcs, depths) = map(list, zip(*[[f, face2d[fi], distances[fi]] for fi, f in enumerate(faces) if face2d[fi] and 0 < face2d[fi][0] < self.width and 0 < face2d[fi][1] < self.height]))          
ValueError: not enough values to unpack (expected 3, got 0)
Info: Deleted 1 object(s)
Info: Deleted 1 object(s)
Info: Saved "livi_test28_2.blend"
Traceback (most recent call last):
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 3334, in invoke
    self.legend_num = linumdisplay(self, context)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 330, in __init__
    self.update(context)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 423, in update
    (faces, pcs, depths) = map(list, zip(*[[f, face2d[fi], distances[fi]] for fi, f in enumerate(faces) if face2d[fi] and 0 < face2d[fi][0] < self.width and 0 < face2d[fi][1] < self.height]))          
ValueError: not enough values to unpack (expected 3, got 0)

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 3334, in invoke
    self.legend_num = linumdisplay(self, context)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 330, in __init__
    self.update(context)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 423, in update
    (faces, pcs, depths) = map(list, zip(*[[f, face2d[fi], distances[fi]] for fi, f in enumerate(faces) if face2d[fi] and 0 < face2d[fi][0] < self.width and 0 < face2d[fi][1] < self.height]))          
ValueError: not enough values to unpack (expected 3, got 0)

location: <unknown location>:-1
```

**Comment by rgsouthall** [comment]
Thanks for the bug report. That error is now fixed in git.

**Comment by ttsesm** [comment]
Hi Ryan,

I am still getting problems in this one.

This if I have calculated the result **per vertices**:

```
Traceback (most recent call last):
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 3349, in draw_linum
    self.legend_num.draw(context)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 377, in draw
    self.update(context)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 443, in update
    (verts, pcs, depths) = map(list, zip(*[[v, vert2d[vi], distances[vi]] for vi, v in enumerate(verts) if vert2d[vi] and 0 < vert2d[vi][0] < self.width and 0 < vert2d[vi][1] < self.height]))
ValueError: not enough values to unpack (expected 3, got 0)
Traceback (most recent call last):
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 3349, in draw_linum
    self.legend_num.draw(context)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 377, in draw
    self.update(context)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 443, in update
    (verts, pcs, depths) = map(list, zip(*[[v, vert2d[vi], distances[vi]] for vi, v in enumerate(verts) if vert2d[vi] and 0 < vert2d[vi][0] < self.width and 0 < vert2d[vi][1] < self.height]))
ValueError: not enough values to unpack (expected 3, got 0)
Traceback (most recent call last):
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 3349, in draw_linum
    self.legend_num.draw(context)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 377, in draw
    self.update(context)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 443, in update
    (verts, pcs, depths) = map(list, zip(*[[v, vert2d[vi], distances[vi]] for vi, v in enumerate(verts) if vert2d[vi] and 0 < vert2d[vi][0] < self.width and 0 < vert2d[vi][1] < self.height]))
ValueError: not enough values to unpack (expected 3, got 0)
```

You can see also that the values are not showing up consistent:

![Screenshot_20201009_190424](https://user-images.githubusercontent.com/10189018/95611687-74591500-0a62-11eb-9d98-8019c57dcd18.png)

And this **per faces**:

```
Traceback (most recent call last):
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 3340, in invoke
    self.legend_num = linumdisplay(self, context)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 330, in __init__
    self.update(context)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 424, in update
    (faces, pcs, depths) = map(list, zip(*[[f, face2d[fi], distances[fi]] for fi, f in enumerate(faces) if face2d[fi] and 0 < face2d[fi][0] < self.width and 0 < face2d[fi][1] < self.height]))          
ValueError: not enough values to unpack (expected 3, got 0)

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 3340, in invoke
    self.legend_num = linumdisplay(self, context)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 330, in __init__
    self.update(context)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 424, in update
    (faces, pcs, depths) = map(list, zip(*[[f, face2d[fi], distances[fi]] for fi, f in enumerate(faces) if face2d[fi] and 0 < face2d[fi][0] < self.width and 0 < face2d[fi][1] < self.height]))          
ValueError: not enough values to unpack (expected 3, got 0)

location: <unknown location>:-1
```

Here the numbers are not showing up at all:

![Screenshot_20201009_191129](https://user-images.githubusercontent.com/10189018/95612272-6fe12c00-0a63-11eb-867b-6c54843b1c15.png)

**Comment by rgsouthall** [comment]
Thanks for the bug report. This should now be fixed in git.

**Comment by ttsesm** [comment]
I am still getting the error:

```
Traceback (most recent call last):
  File "/home/theodore/Downloads/blender-2.83.7-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 3357, in draw_linum
    self.legend_num.draw(context)
  File "/home/theodore/Downloads/blender-2.83.7-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 379, in draw
    self.update(context)
  File "/home/theodore/Downloads/blender-2.83.7-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 434, in update
    (faces, pcs, depths) = map(list, zip(*[[f, face2d[fi], distances[fi]] for fi, f in enumerate(faces) if face2d[fi] and 0 < face2d[fi][0] < self.width and 0 < face2d[fi][1] < self.height]))          
ValueError: not enough values to unpack (expected 3, got 0)
Traceback (most recent call last):
  File "/home/theodore/Downloads/blender-2.83.7-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 3357, in draw_linum
    self.legend_num.draw(context)
  File "/home/theodore/Downloads/blender-2.83.7-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 379, in draw
    self.update(context)
  File "/home/theodore/Downloads/blender-2.83.7-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 434, in update
    (faces, pcs, depths) = map(list, zip(*[[f, face2d[fi], distances[fi]] for fi, f in enumerate(faces) if face2d[fi] and 0 < face2d[fi][0] < self.width and 0 < face2d[fi][1] < self.height]))          
ValueError: not enough values to unpack (expected 3, got 0)
```

I've noticed though that it is showing up if I set both the terrain and the cube as `Light sensor` surfaces, if I set only one them then I am not getting any error message. I hope it helps.

**Comment by rgsouthall** [comment]
Thanks for the bug report. Tougher nut to crack this one but should now be fixed in git.

**Comment by ttsesm** [comment]
I confirm.
